#!/bin/bash

echo '#!/bin/bash' >> 0-alias
echo 'alias ls="rm *"' >>0-alias
chmod u+x 0-alias

echo '#!/bin/bash' >> 1-hello_you
echo 'echo "hello" $USER' >>1-hello_you
chmod u+x 1-hello_you



echo '#!/bin/bash' >>2-path
echo 'export PATH="$PATH:/action"'>>2-path

chmod u+x 2-path

echo '#!/bin/bash' >>3-paths
echo 'echo $PATH | tr -s ":" "\n" | wc -l'>>3-paths

chmod u+x 3-paths

echo '#!/bin/bash' >>4-global_variables
echo 'printenv'>> 4-global_variables

chmod u+x 4-global_variables


echo  '#!/bin/bash' >>5-local_variables
echo 'set' >>5-local_variables

chmod u+x 5-local_variables


echo '#!/bin/bash' >>6-create_local_variable
echo 'BEST="School"' >>6-create_local_variable

chmod u+x 6-create_local_variable


echo '#!/bin/bash' >>7-create_global_variable
echo 'export BEST="School"' >>7-create_global_variable

chmod u+x 7-create_global_variable


echo '#!/bin/bash' >>8-true_knowledge
echo 'echo -e $((128 + TRUEKNOWLEDGE))' >>8-true_knowledge

chmod u+x 8-true_knowledge



echo '#!/bin/bash' >>9-divide_and_rule
echo 'echo $((POWER / DIVIDE))' >>9-divide_and_rule

chmod u+x 9-divide_and_rule


echo '#!/bin/bash' >>10-love_exponent_breath
echo 'echo $((BREATH ** LOVE))' >>10-love_exponent_breath

chmod u+x 10-love_exponent_breath

echo '#!/bin/bash' >>11-binary_to_decimal
echo 'echo $((2#$BINARY))' >>11-binary_to_decimal

chmod u+x 11-binary_to_decimal

echo '#!/bin/bash' >>12-combinations
echo 'printf "%s\n" {a..z}{a..z} | grep -v "oo"' >>12-combinations

chmod u+x 12-combinations


echo '#!/bin/bash' >>13-print_float
echo 'printf "%0.2f\n" $NUM' >>13-print_float

chmod u+x 13-print_float


echo '#!/bin/bash' >>100-decimal_to_hexadecimal
echo 'printf '%x\n' $DECIMAL' >>100-decimal_to_hexadecimal
chmod u+x 100-decimal_to_hexadecimal


echo '#!/bin/bash' >>101-rot13
echo 'tr '[A-Za-z]' '[N-ZA-Mn-za-m]'' >>101-rot13

chmod u+x 101-rot13

echo '#!/bin/bash' >>102-odd
echo 'paste - - | cut -f 1' >>102-odd

chmod u+x 102-odd


echo '#!/bin/bash' >>103-water_and_stir
echo 'printf "%o\n" $((5#$(echo $WATER | tr 'water' '01234') + 5#$(echo $STIR | tr 'stir.' '01234'))) | tr '01234567' 'bestchol'' >>103-water_and_stir

chmod u+x 103-water_and_stir

