#!/bin/bash

echo '#!/bin/bash'>>13-change_group
echo 'chgrp school hello'>>13-change_group
chmod u+x 13-change_group

echo '#!/bin/bash'>>100-change_owner_and_group
echo 'chown vincent:staff *'>>100-change_owner_and_group
chmod u+x 100-change_owner_and_group

echo '#!/bin/bash'>>101-symbolic_link_permissions
echo 'Chown -h Vincent:staff _hello'>>101-symbolic_link_permissions
chmod u+x 101-symbolic_link_permissions

echo '#!/bin/bash'>>102-if_only 
echo 'find / -user guillaume -exec chown betty hello'>>102-if_only 
chmod u+x 102-if_only 

echo '#!/bin/bash'>>103-Star_Wars
echo 'telnet towel. blinkenlights. nl'>>103-Star_Wars
chmod u+x 103-Star_Wars
